name: Docker image buildx and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: docker image build
        run: docker image build -t littledouzi/flask-redis:latest
      -
        name: list docker image
        run: docker image ls
